name: GastroGrid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  charts_flutter: 0.12.0
  cloud_firestore: ^4.17.0
  custom_navigation_bar: ^0.8.2
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.7.2
  flat_3d_button: ^1.0.3
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.6.0
  google_nav_bar: ^5.0.6
  google_place: ^0.4.7
  image_picker: ^1.1.0
  ionicons: ^0.2.2
  line_icons: ^2.0.3
  location: ^6.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  firebase_app_check: ^0.2.2+6 
  image_picker_web: ^3.1.1
  universal_html: ^2.2.4
  geolocator: ^12.0.0
  encrypt: ^5.0.3
  flutter_stripe: ^4.0.0
  cloud_functions: ^4.7.5
  stripe_platform_interface: ^4.0.0
  flutter_braintree: ^4.0.0
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconApp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/imagine_profil1.jpeg
    - assets/imagine_profil2.jpeg
    - assets/imaginea1.jpeg
    - assets/imaginea2.jpeg
    - assets/imaginea3.jpeg
    - assets/imaginea4.jpeg
    - assets/imaginea5.jpeg
    - assets/imaginea6.jpeg
