name: gastrogrid_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  custom_navigation_bar: ^0.8.2
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flat_3d_button: ^1.0.3
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.6.0
  google_nav_bar: ^5.0.6
  google_place: ^0.4.7
  ionicons: ^0.2.2
  line_icons: ^2.0.3
  location: ^5.0.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
